name: teamwork

on:
  pull_request:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ensure this project runs
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: "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"
          TEAMWORK_URI: "https://corebiz87.eu.teamwork.com/"
          TEAMWORK_API_TOKEN: "test_api_token"
          AUTOMATIC_TAGGING: true
          BOARD_COLUMN_OPENED: "PR Open"
          BOARD_COLUMN_MERGED: "Ready to Test"
          BOARD_COLUMN_CLOSED: "Rejected"
